### ISSUE TITLE
HybridCLRGlobalSettings 中部分项是否可以放到 Runtime 下面。

### ISSUE THREAD

**Issue by Roland0511** [focus-creative-games/hybridclr_trial#10]
HybridCLRGlobalSettings 这个类中的部分配置项，比如像`hotfixAssemblies`，`AOTMetadataDlls` 这些。是否可以考虑放到Runtime下面，这些变量在 编译(Editor) 和 运行时加载dll(Runtime) 的时候大多都需要使用相同的值。
现在这个配置虽然做成了asset但是Runtime情况下并无法访问到，就不得不在Runtime的代码中再抄写一份一样的。维护起来感觉会不太方便。修改也容易出错。

**Comment by pirunxi** [comment]
确实是个问题，我们也考虑到了。但是放到Runtime又不是特别妥当。我们再考虑一下。
