### ISSUE TITLE
热更新改动

### ISSUE THREAD

**Issue by HeNuoScott** [focus-creative-games/hybridclr_trial#15]
强烈建议   开发者团队后续攻破在unity编辑器运行时热更新,,就想ET一样 ctrl+R 直接进行热更

**Comment by pirunxi** [comment]
这东西是违背规范的，但我们后续会考虑能不能让这种事情简单一点

**Comment by Bian-Sh** [comment]
简单的，首先 il2cpp 发生在打包执行程序的过程中，所以编辑器咱不能热更dll
然后呢，也许你要的只是给 build dll ab 的菜单 ”Build/buildassetbundle“ 一个 ctrl+r 的快捷键吧
