### ISSUE TITLE
2020.3.3版本 windows打包报错

### ISSUE THREAD

**Issue by zs9024** [focus-creative-games/hybridclr_trial#16]
Exception: Failed running .../hybridclr_trial/HybridCLRData/LocalIl2CppData/il2cpp/build/BeeSettings/offline/bee.exe --no-colors --

**Comment by zs9024** [comment]
已解决：将20.3.3安装目录下对应的build目录替换掉LocalIl2CppData下目录
建议文档说明一下

**Comment by pirunxi** [comment]
好的！ 不过建议不要用低版本，因为ios上有问题。
