### ISSUE TITLE
Reporter/Create命令出错

### ISSUE THREAD

**Issue by ProtectedI** [focus-creative-games/hybridclr_trial#18]
点击 Reporter/Create创建Reporter对象到Hierarchy上后，发现Reporter的Images都是空，没有加载到图标

**Comment by pirunxi** [comment]
确实是空的，不过好像也不影响运行。先这样子吧。

**Comment by ProtectedI** [comment]
空的原因是那些图片的位置和它获取的路径没对上，解决办法：将安装好的UnityLogViewer 中Images 文件夹，拖至 Runtime文件夹下面即可.

**Comment by pirunxi** [comment]
pr给我们吧。少年

**Comment by ProtectedI** [comment]
啥意思啊 老哥 ，怎么操作？？

**Comment by pirunxi** [comment]
pr是pull request的缩写。 没事，我们已经如你建议搞定了。

**Comment by ProtectedI** [comment]
ok   感谢  get到了
