### ISSUE TITLE
实例工程install完了之后build就报错，这个还和visual studio版本有关系？

### ISSUE THREAD

**Issue by jimmmmmmmmmyfunnnnnnny** [focus-creative-games/hybridclr_trial#19]
![image](https://user-images.githubusercontent.com/26768352/199696032-67ec4852-342a-45c6-89ad-1c4e16360d29.png)

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
版本是2020.3.33f1的

**Comment by pirunxi** [comment]
建议package更到最新，再install最新，再打包。还有问题可去新手群咨询
