### ISSUE TITLE
打包失败 Exception: Unity.IL2CPP.Building.BuilderFailedException

### ISSUE THREAD

**Issue by jueane** [focus-creative-games/hybridclr_trial#26]
HybirdCLR -> Build -> Win64，一段时间后出现如下报错：

Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe /out:"D:\develop\UnityProjectRoot\hybridclr_trial\Library\il2cpp_cache\linkresult_9D0CA52E45C1B8AD75E5B7A16EC3D556\GameAssembly.dll" /ignore:4206 /DEBUG:FASTLINK /INCREMENTAL:NO /LARGEADDRESSAWARE /NXCOMPAT /DYNAMICBASE /NOLOGO /TLBID:1 /HIGHENTROPYVA /DLL /IGNORE:4104 /NODEFAULTLIB:uuid.lib "kernel32.lib" "user32.lib" "advapi32.lib" "ole32.lib" "oleaut32.lib" "Shell32.lib" "Crypt32.lib" "psapi.lib" "version.lib" "MsWSock.lib" "ws2_32.lib" "Iphlpapi.lib" "Dbghelp.lib" "C:\Program Files\Unity\Hub\Editor\2020.3.36f1\Editor\Data\PlaybackEngines\WindowsStandaloneSupport\Variations\win64_nondevelopment_il2cpp\baselib.dll.lib" /LIBPATH:"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\lib\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64" /SUBSYSTEM:WINDOWS @"C:\Users\Administrator\AppData\Local\Temp\tmpCAE4.tmp"

Creating library D:\develop\UnityProjectRoot\hybridclr_trial\Library\il2cpp_cache\linkresult_9D0CA52E45C1B8AD75E5B7A16EC3D556\GameAssembly.lib and object D:\develop\UnityProjectRoot\hybridclr_trial\Library\il2cpp_cache\linkresult_9D0CA52E45C1B8AD75E5B7A16EC3D556\GameAssembly.exp

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles)
   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, BuildingOptions buildingOptions, Boolean throwExceptions)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <786b546700bc48b68852821de5e46ca9>:0)
DesktopStandalonePostProcessor.RunIL2CPP (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditorInternal.IIl2CppPlatformProvider il2cppPlatformProvider, System.Collections.Generic.List`1[T] cppPlugins) (at <786b546700bc48b68852821de5e46ca9>:0)
DesktopStandalonePostProcessor.SetupStagingArea (UnityEditor.Modules.BuildPostProcessArgs args, System.Collections.Generic.HashSet`1[T] filesToNotOverwrite) (at <786b546700bc48b68852821de5e46ca9>:0)
DesktopStandalonePostProcessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <786b546700bc48b68852821de5e46ca9>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
DesktopStandalonePostProcessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <786b546700bc48b68852821de5e46ca9>:0)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
HybridCLR.Editor.BuildPlayerCommand:Build_Win64() (at Assets/Editor/HybridCLR/BuildPlayerCommand.cs:52)

**Comment by NaTHIeL1** [comment]
我也遇到了这个问题，请问你是如何解决的

**Comment by jueane** [comment]
> 我也遇到了这个问题，请问你是如何解决的

不记得了，不过我现在用的2019，可能是这个版本问题吧
