### ISSUE TITLE
HybridCLR Installer卡主或报错

### ISSUE THREAD

**Issue by OopsAngela** [focus-creative-games/hybridclr_trial#32]
![image](https://github.com/user-attachments/assets/d6656289-9caa-4487-a495-c40799230307)
卡好几分钟以后报错：
![image](https://github.com/user-attachments/assets/6db13f5b-c3c6-4741-a942-9871826e4934)
空工程，示例工程均无法安装

**Comment by pirunxi** [comment]
这个问题如果能稳定复现可以提交我们。但大概率跟本地环境有关系。你只可以考虑删除HybridCLRData目录后再试。如果还有问题，可以去新手群反馈给我们
